[project]
id = "<buildpack ID>"
name = "<buildpack name>"
version = "<buildpack version>"

# optional fields
authors = []
spec = "v3" # defaults to v3
documentation = ""
license = ""

# gitignore pattern, exclude and include are mutually exclusive
exclude = [""]
include = [""]

package = false # to be added with buildpack registry RFC, false denotes not to accidentally publish

[extensions]
osbapi = true

[[buildpacks]]
id = "io.buildpacks.ruby"
version = "1.0.0"
# uri and path are mutually exclusive
uri = "<url or path to the buildpack (optional default=urn:buildpack:<id>)"
path = "<path to an inline buildpack (optional)"

[[buildpacks.stacks]]
id = "io.buildpacks.stacks.bionic"

# implicit order unless this is specified
[[buildpacks.order]]
group = [
  { id = "io.buildpacks.node", version = "0.0.5", optional = true },
  { id = "io.buildpacks.mri", version = "0.0.7" },
  { id = "io.buildpacks.bundler", version = "2.0.2" },
]

[[buildpacks]]
id = "io.buildpacks.mri"
version = "0.0.7"
path = "./mri-cnb"

[[buildpacks]]
id = "io.buildpacks.bundler"
version = "2.0.2"
path = "./bundler-cnb"

[[patch]]
id = "io.buildpacks.mri"
path = "mri"

[[image]]
# by default inherits from project.name
name = "..."
path = "."
stack = "<id>" # default stack to build against
  [image.env]
  key1 = "value"
  key2 = "value"
  [[image.processes]]
  name = "web"
  cmd = "..."
  [[image.processes]]
  name = "worker"
  cmd = "..."

# can use globs for pattern matching here
[workspace]
members = []
# `pack build` will build images for these by default 
default-members = []
exclude = []

# keys in here are not validated
[metadata]
# place to store vendor specific metadata
[metadata.heroku]
addons = {
  postgresql = "9.6"
}
