[project]
id = "org.cloudfoundry.nodejs"
name = "CloudFoundry Node.js Buildpack"
version = "0.0.1"

[[buildpacks.stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[buildpacks.stacks]]
id = "io.buildpacks.stacks.bionic"

[workspace]
members = [
  "nodejs-cnb",
  "yarn-cnb",
  "npm-cnb"
]
