[project]
id = "org.cloudfoundry.nodejs"
name = "CloudFoundry Node.js Buildpack"
version = "0.0.1"

[[buildpacks.stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[buildpacks.stacks]]
id = "io.buildpacks.stacks.bionic"

[[buildpacks.order]]
group = [
  { id = "org.cloudfoundry.node-engine", version = "0.0.11" },
  { id = "org.cloudfoundry.npm", version = "0.0.8" },
]

[[buildpacks.order]]
group = [
  { id = "org.cloudfoundry.node-engine", version = "0.0.11" },
  { id = "org.cloudfoundry.yarn", version = "0.0.6" },
]

[workspace]
members = [
  "nodejs-cnb",
  "yarn-cnb",
  "npm-cnb"
]
